### ISSUE TITLE
For publishingtools related solutions make sure to describe the repository structure used when deploying

### ISSUE THREAD

**Issue by xmonader** [threefoldfoundation/info_tfgrid_sdk#215]
For publishingtools related solutions make sure to describe the repository structure used when deploying. how the website, blog, wiki repos should look like, link to the publishingtools docs.. etc

**Comment by despiegk** [comment]
this is not clear? what is meant with this

**Comment by xmonader** [comment]
> this is not clear? what is meant with this

the solutions for wiki, blog, website all of them require the git repo content used to be in a specific format to actually have a successful deployment so these needs to be described

**Comment by xmonader** [comment]
here's a work in progress to double check next week
https://github.com/crystaluniverse/publishingtools/commit/e3f49f776406543825077bd434a9322ee7033688

**Comment by sasha-astiadi** [comment]
done by asking users to fork a template on evdc - marketplace wiki, website, blog tutorials
 https://github.com/threefoldfoundation/website_example
 https://github.com/threefoldfoundation/blog_example
 https://github.com/threefoldfoundation/wiki_example
