### ISSUE TITLE
update the hugo website tutorial

### ISSUE THREAD

**Issue by xmonader** [threefoldfoundation/info_tfgrid_sdk#238]
https://github.com/threefoldfoundation/info_gridmanual/blob/development/src/tutorials/huge_website_advanced.md

**Comment by RafyAmgadBenjamin** [comment]
#### Fixed 
Updated the docs, the screenshots, and tested the whole scenario.
#### Commit id 
6a22d5e9baa02bdeb1d3af9eeebe97e2eea66112
#### Branch
`development_huge_website_updates`

#### Pr
https://github.com/threefoldfoundation/info_gridmanual/pull/240

**Comment by zaibon** [comment]
I didn't any change in the side bar? So it seems the tutorial is still unreachable from anywhere in the manual ?
