### ISSUE TITLE
missing images on get_freetft page

### ISSUE THREAD

**Issue by rkhamis** [threefoldfoundation/info_tfgrid_sdk#271]
![missing2](https://user-images.githubusercontent.com/8425762/93863945-78481180-fcc4-11ea-8a2c-47eb940efe22.jpg)
![missing](https://user-images.githubusercontent.com/8425762/93863961-7da55c00-fcc4-11ea-8af4-f28230aea7a7.jpg)

on https://manual.threefold.io/#/getting_freetft

**Comment by sasha-astiadi** [comment]
no longer used
