### ISSUE TITLE
resize the image to a smaller form - does not need to be this large

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldfoundation/info_tfgrid_sdk#71]
https://github.com/threefoldfoundation/info_tfgridsdk/blob/925ec74dd273ce4b084f5291a794339170b9bc4c/src/gettingstarted/sdk_install.md#L33-L33

**Comment by despiegk** [comment]
all images should be looked at
the size... can be used

**Comment by despiegk** [comment]
also in info...
