### ISSUE TITLE
Tell users to start docker daemon before starting Threebot container

### ISSUE THREAD

**Issue by maximevanhees** [threefoldfoundation/info_tfgrid_sdk#77]
http://09a453a7.ngrok.io/sdk/index.html#/3sdk_use?id=using-the-3botconnect-app-words-mnemonics tells how to start a Threebot Container. This gives the following error when the Docker daemon is not running (yet).

![image](https://user-images.githubusercontent.com/25902145/80363285-4dc46a80-8884-11ea-8c32-86016e243bd1.png)

As the wiki's are made for everyone, it could be an idea to also tell "less" technical people how to start the docker daemon (based on the OS they use).

**Comment by despiegk** [comment]
there needs to be a proper feedback message in stead of this low level message in the sdk

**Comment by despiegk** [comment]
need to ask for feature request for 3sdk on core jumpscale
